### ISSUE TITLE
Better definition of project?

### ISSUE THREAD

**Issue by bits3rpent** [kamhix/todoist-linux#1]
Hey, glad to see someone has taken initiative with trying to get Todoist on the Linux desktop. However, I believe a little clarification is needed. 
1. Specify if this is or is not the official "Todoist for Linux"
2. If not, specify what it does, and how.

Best Wishes!

**Comment by kamhix** [comment]
Thanks @bits3rpent , I took your advice into consideration. 
The project is an unofficial port of Todoist on Linux. 
What it does is to offer every features of the Web version of Todoist or the Android one. It use nwjs to embed the web version in a window container. 
I have already updated it.
Thanks again for your feedback.

**Comment by bits3rpent** [comment]
Much appreciated my friend, thank you for the quick response!

**Comment by kamhix** [comment]
you're welcome
