### ISSUE TITLE
Can't re open application from Ubuntu dock after minimizing

### ISSUE THREAD

**Issue by Jont828** [kamhix/todoist-linux#27]
After I minimize the app, clicking on it from the dock doesn't do anything. The only way to get it back is to use the tray icon.

**Comment by gabrielcs** [comment]
Same here.

**Comment by krydos** [comment]
hey guys. I had the same issue and wasn't able to fix it with nw.js (the error looks like something nw.js related. The app is fine). 

I've made my own wrapper on the web version of todoist here - https://github.com/KryDos/todoist-linux

Restoring from Tray works. There is also global shortcut added (the one that important for me) to quick add a task. 

Let me know if  it can be useful you.

**Comment by Jont828** [comment]
This issue seems to be fixed in the latest update/version
