### ISSUE TITLE
Can't zoom in/out on high DPI displays to make the font readable

### ISSUE THREAD

**Issue by Jont828** [kamhix/todoist-linux#29]
I have a 2560 x 1440 display and I'm running Gnome with Arch Linux on a 14 inch laptop and everything in the app is very tiny as a result. I have my OS scale everything up, but the app didn't respond to that. Ctrl +/-  doesn't seem to do anything either. As of now, the app is essentially unusable on my computer without reading glasses.

**Comment by krydos** [comment]
hey @Jont828 

Take a look at this package - https://github.com/KryDos/todoist-linux

It's pretty much the same wrapper on todoist's web version but use electron instead of nwjs. I've tried to fix high DPI issues there. It would be great if you let me know if it works for you (no ctrl+<scroll> though)

**Comment by kamhix** [comment]
Hello @Jont828 , I know it's been a long time, but I was busy and I lost the new changes files. I have more time now and I built a new version with zoom features. If you still using Todoist maybe you can try and give me some feedback.
Basically it's work with Ctrl + Numpad+ or Ctrl +Numpad- or using the menu.

@KryDos thanks for helping them and sorry the absence. I've also thought about moving to electron but never take the gap.

**Comment by Jont828** [comment]
Thank you so much! I'm running Arch, though, so do you think it would be possible to get this into the AUR? There's a [Todoist client in the AUR](https://aur.archlinux.org/packages/todoist/), but it seems like it's been abandoned.

**Comment by Jont828** [comment]
Also, just a minor suggestion, but it would be cool if you could collapse the menu at the top and have it appear when you hover, or something.

**Comment by kamhix** [comment]
I will check for the AUR, that should be possible. For the menu, which one are you talking about. The Todoist one or the app one with zoom and options?

**Comment by Jont828** [comment]
The zoom and options menu
