### ISSUE TITLE
No icon in cairo dock

### ISSUE THREAD

**Issue by jackxb** [kamhix/todoist-linux#5]
Hi kamhix!

in my system mint 17.1 in cairo dock does not display a running application. In the standard taskbar okay. Thank you.

**Comment by Milozzy** [comment]
Same here on Gnome-Shell: cannot pin to the side dock.

**Comment by kamhix** [comment]
I managed to reproduce the bug and actually the icon does not appear. It seems to be related to the WM_CLASS attribute that is not specified by nwjs. I'm still working on it! 
I added tray system so maybe it can be used as a workaround.

**Comment by Milozzy** [comment]
Can you please update the package on http://todoistlinux.kamhix.com?

Thank you very much

**Comment by kamhix** [comment]
Oops, 
I did it. thanks for the reminder.

**Comment by Milozzy** [comment]
No man, thank you for your work!! Thanks!
