### ISSUE TITLE
http://todoistlinux.kamhix.com doesn't exist anymore

### ISSUE THREAD

**Issue by gawen** [kamhix/todoist-linux#8]
Hello,

As the title says. You might want to change or remove your project website.

Cheers

**Comment by kamhix** [comment]
Yes. Sorry for the inconvenience. I have been so busy and I lost the kamhix.com domain :sob: 
It's available on my personnel domain at this url. 
http://todoistlinux.hakimouake.com

I have already changed the link in the description and readme.

Best regards,
kamhix

**Comment by gawen** [comment]
Thanks.
