### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by jnor** [kamhix/todoist-linux#9]
Hi, 

Running arch on newish macbook pro and the application is very small on HiDPI display.
Any suggestion?

**Comment by kamhix** [comment]
Are you using the prebuilt version from the website ?

**Comment by jnor** [comment]
yes grabbed it here http://todoistlinux.hakimouake.com/

Edit: ok, seems fine when I use the github version =)

**Comment by kamhix** [comment]
cool ! I think it related to the nwjs (node-webkit) version. I will update it as soon as possible.
